from __future__ import annotations

import difflib
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SearchHit:
    path: Path
    line_no: int
    line: str


def iter_text_files(root_dir: Path, extensions: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for path in root_dir.rglob("*"):
        if path.is_file() and path.suffix in extensions:
            files.append(path)
    return sorted(files)


def search_symbol_usage(
    root_dir: Path,
    symbol: str,
    extensions: tuple[str, ...] = (".py", ".md", ".json"),
) -> list[SearchHit]:
    hits: list[SearchHit] = []
    for path in iter_text_files(root_dir, extensions):
        content = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        for idx, line in enumerate(content, start=1):
            if symbol in line:
                hits.append(SearchHit(path=path, line_no=idx, line=line.strip()))
    return hits


def build_usage_report(symbol: str, hits: list[SearchHit], root_dir: Path) -> str:
    rows = [
        "# Day 34 Usage Report",
        "",
        f"Symbol: `{symbol}`",
        f"Total hits: **{len(hits)}**",
        "",
        "## Matches",
    ]
    if not hits:
        rows.append("- No matches found.")
    else:
        for hit in hits:
            rel = hit.path.relative_to(root_dir)
            rows.append(f"- `{rel}:{hit.line_no}` - `{hit.line}`")
    rows.append("")
    rows.append("_Generated automatically by day_34_file_assistant._")
    return "\n".join(rows) + "\n"


def render_diff(old: str, new: str, rel_path: str) -> str:
    if old == new:
        return f"No changes for {rel_path}."
    diff = difflib.unified_diff(
        old.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile=f"a/{rel_path}",
        tofile=f"b/{rel_path}",
    )
    return "".join(diff)


def write_file(path: Path, content: str) -> str:
    old_content = path.read_text(encoding="utf-8") if path.exists() else ""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return render_diff(old_content, content, rel_path=str(path))


def build_homeworks_index(homeworks_dir: Path) -> str:
    lines = [
        "# Homeworks Index",
        "",
        "Auto-generated index for daily homework markdown files.",
        "",
        "## Days",
    ]
    day_files = sorted(homeworks_dir.glob("day_*.md"))
    for file_path in day_files:
        title = "Без заголовка"
        for line in file_path.read_text(encoding="utf-8", errors="ignore").splitlines():
            clean = line.strip()
            if clean:
                title = clean
                break
        lines.append(f"- `{file_path.name}` - {title}")
    lines.append("")
    lines.append("_Generated by day_34_file_assistant._")
    return "\n".join(lines) + "\n"


def run_demo(symbol: str = "LocalJsonContextProvider") -> None:
    repo_root = Path(__file__).resolve().parents[4]
    homeworks_dir = repo_root / "homeworks"
    src_dir = homeworks_dir / "src"

    hits = search_symbol_usage(src_dir, symbol=symbol)
    usage_report = build_usage_report(symbol=symbol, hits=hits, root_dir=repo_root)
    usage_report_path = homeworks_dir / "day_34_usage_report.md"
    usage_diff = write_file(usage_report_path, usage_report)

    index_path = homeworks_dir / "README.md"
    index_content = build_homeworks_index(homeworks_dir)
    index_diff = write_file(index_path, index_content)

    print("=== Scenario 1: Symbol usage search ===")
    print(f"Symbol: {symbol}")
    print(f"Matches found: {len(hits)}")
    print(f"Report written: {usage_report_path}")
    print("")
    print("=== Scenario 2: Documentation update ===")
    print(f"Index updated: {index_path}")
    print("")
    print("=== Diff preview ===")
    print(usage_diff)
    print(index_diff)


def main() -> None:
    run_demo()


if __name__ == "__main__":
    main()
